# site settings
title: Slava Romanov
subtitle: Multimedia Artist
email: davinel000@gmail.com
description: Working hard to rest smart with cozy lighting and vintage gadgets
#baseurl: #"/test" # the subpath of your site, e.g. /blog
imagefolder: "https://filedn.com/lGT3vQOeVHQFjjI0lPsYmHS/images" #public folder of the website (PCloud) name is added to the address

url: # the base hostname & protocol for your site
author: Viacheslav Romanov
street_address: Huder str. 1e
city: Bremen
state: HB
zip_code: 28197
country: Germany
phone: (+49) 15211091721

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/davinel000
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/viacheslav.romanov.9/ 
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

# plugins are here (=bundle install= to install, copy to _Plugins folder)
plugins: 
- jekyll-datapage-generator

# generating pages
page_gen:
- data: 'portfolio.works' #IMPORTANT when you have several tables in your yaml portfolio
  template: 'page'
  name: 'title'
  dir: 'projects'
  index_files: true


exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
