# site settings
title: Slava Romanov
subtitle: Data Artist & Multimedia Developer
email: davinel000@gmail.com
description: working hard to rest smart with cozy lighting and vintage gadgets
baseurl: "" #"/test" # the subpath of your site, e.g. /blog
imagefolder: "/assets/images/portfolio" # "https://filedn.com/lGT3vQOeVHQFjjI0lPsYmHS/images" #public folder of the website (PCloud) name is added to the address

url: "https://davinel000.github.io"  
author: Slava Romanov
street_address: 
city: Bremen
state: HB
zip_code: 
country: Germany
phone: 

# homepage tiles
tiles-source: both # accepts "posts" or "pages" or "both" (update of 16.09.2023)
tiles-count: 12

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/davinel000
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/davinel000/
  LinkedIn: https://www.linkedin.com/in/slavaromanov/
  Twitter: 
  Facebook: https://www.facebook.com/viacheslav.romanov.9/ 
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

future: true

# plugins:
# - jekyll-datapage-generator
# # - pagemaster

# page_gen:
# - data: 'portfolio.works'
#   template: 'project'
#   dir: 'projects'
#   index_files: true
#   name: 'title'
  # title: 'title'

# collections:
  # - portfolio      
  # projects:
  #   output: true
  #   source: 'portfolio.yml'
  #   id_key: 'works.id'
  #   layout: 'project'
  # data.portfolio.works:
  #   output: true


exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
