# site settings
title: Forty
subtitle: by HTML5 UP
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
<<<<<<< Updated upstream
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
=======
author: Viacheslav Romanov
street_address: 
city: Bremen
state: HB
zip_code: 28197
country: Germany
phone: 
>>>>>>> Stashed changes

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
<<<<<<< Updated upstream
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
=======
  Google-Plus: 
  Instagram: https://www.instagram.com/davinel000/
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/viacheslav.romanov.9/ 
>>>>>>> Stashed changes
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

<<<<<<< Updated upstream
=======
# plugins:
# - jekyll-datapage-generator
# # - pagemaster

# page_gen:
# - data: 'portfolio.works'
#   template: 'project'
#   dir: 'projects'
#   index_files: true
#   name: 'title'
  # title: 'title'

# collections:
  # - portfolio      
  # projects:
  #   output: true
  #   source: 'portfolio.yml'
  #   id_key: 'works.id'
  #   layout: 'project'
  # data.portfolio.works:
  #   output: true

include:
  - "_js"

>>>>>>> Stashed changes
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
